version: '3.11'

services:
  web:
    build: .
    command: python app.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - "5000:5000"
    env_file:
      - ./.env.dev